### ISSUE TITLE
Пункт 9

### ISSUE THREAD

**Issue by danya-andrienko** [pupenasan/cmputernetwork#9]
У пункті 9 я думаю треба більш детально пояснити додавання нового маршрутного запису
 route add 192.168.1.0 mask 255.255.255.0 192.168.10.106 if 15 типу що за що відповідає у цій команді тому що у мене це не працювало поки я не залишив порожнім поле if.

**Comment by pupenasan** [comment]
А гляньте зараз. https://pupenasan.github.io/cmputernetwork/lab/3.html

**Comment by danya-andrienko** [comment]
Дякую Вам так набагато краще, та загалом дякую за цей предмет він дуже цікавий)
